### ISSUE TITLE
Add ability to link directly to "cells"

### ISSUE THREAD

**Issue by cjosephson** [jlab-sensing/ENTS-backend#266]
Right now if I want to show somebody specific data, they have to click the dropdown and select the 'cell'. Instead, we should be able to directly link to a cell(s)--even better if we can link to a query range so I can link to a specific data view of certain cell(s) during a specific time range.  

Also, we should probably change the name from "cell" to "logger" since soon enough a bunch of these will not have an MFC attached and will be logging data for other sensors

**Comment by jmadden173** [comment]
Closed as part of #323
