### ISSUE TITLE
Migrate schema from cells to loggers

### ISSUE THREAD

**Issue by aaron-wu1** [jlab-sensing/ENTS-backend#315]
For the transition to OSP, not all sensing applications on the platform are going to include MFCs. Currently, cells are used as a structure to store information about the sensors attached to the logging device. For clarity, this should be renamed as logger and refactored with the relevant fields

**Comment by jmadden173** [comment]
I think that we should stick with separation of logging device and cell/sensor. Lets instead working on transitioning to the new sensor interface.
